version: "3.8"

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: chat-mongodb
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hlanz
      MONGO_INITDB_DATABASE: chat
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express
    container_name: chat-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hlanz
      ME_CONFIG_MONGODB_URL: mongodb://root:hlanz@chat-mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hlanz
    depends_on:
      - mongodb
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongodb_data:
